//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beadando_NKJBXO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arak
    {
        public int ArID { get; set; }
        public int TermekFK { get; set; }
        public int BoltFK { get; set; }
        public Nullable<int> Ar { get; set; }
    
        public virtual Boltok Boltok { get; set; }
        public virtual Termekek Termekek { get; set; }
    }
}
